### ISSUE TITLE
`event.preventDefault` prevents copying of webpage text

### ISSUE THREAD

**Issue by jD2R** [thelegendski/thumbnail.js#1]
Promise pointed out to me that by using thumbnail.js (ski.js is actually the culprit), copying text on content of the webpage using ctrl-c is compromised. Not sure if there would be a proper fix to this, but we suspect the cause is coming from the use of `event.preventDefault` in the keypress event functions in ski.js.

Try copying text from [this webpage](https://www.khanacademy.org/computer-programming/top-down-movement-tt/6090508842876928).

**Comment by thelegendski** [comment]
i have no clue how to fix it quickly. like, literally no idea. the issue is that when a key event occurs its target is not the canvas element, it is the body element as a whole. from my testin', it should work, but it obviously doesn't. i would have to force you to click inside the canvas whenever you wanted to interact usin' the keyboard which will take some time. expect to have a patch by April 7th.

ski.js is a poorly developed library. i thought it was rock solid in the`1.6.1` release, but issue after issue PR after PR brings up the fact that there's a lot of maintenance that needs to be done. `lerpColor` doesn't work properly `clear` & `background` are affected by transformations. no documentation. `text` still doesn't have proper `width` an' `height` parameters. i appreciate every issue, so in a long-winded manner, thank you for reportin' this.

**Comment by saejin-moon** [comment]
i think this has been fixed, :D! check v1.1.0 of ski.js.
